---
dist: xenial
language: python
python: 3.7

services:
  - docker

before_install:
  - bash tools/scripts/setup-env.sh
  - pip install --upgrade pip setuptools

install: pip install tox-travis

script: tox
